# Generated by Django 3.1.4 on 2021-01-16 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aki', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='akin',
            options={'verbose_name': 'Игра', 'verbose_name_plural': 'Игры'},
        ),
        migrations.AlterModelOptions(
            name='profiles',
            options={'verbose_name': 'Профиль', 'verbose_name_plural': 'Профили'},
        ),
        migrations.AlterField(
            model_name='profiles',
            name='how_left',
            field=models.IntegerField(verbose_name='Осталось игр'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='how_start',
            field=models.IntegerField(verbose_name='Кол-во игр'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='img',
            field=models.CharField(max_length=511),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='snf',
            field=models.TextField(verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='user_id',
            field=models.IntegerField(unique=True, verbose_name='ID персоны'),
        ),
    ]
