# Generated by Django 3.1.4 on 2021-01-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aki', '0002_auto_20210116_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='referals',
            field=models.TextField(null=True),
        ),
    ]
