# Generated by Django 3.1.4 on 2021-01-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aki', '0003_profiles_referals'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='how_referals',
            field=models.IntegerField(null=True),
        ),
    ]
