# Generated by Django 3.1.4 on 2021-01-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aki', '0004_profiles_how_referals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='how_referals',
            field=models.IntegerField(null=True, verbose_name='Кол-во рефералов'),
        ),
    ]
