# Generated by Django 2.2 on 2021-02-28 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aki', '0006_profiles_who_referal'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='isDonate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profiles',
            name='isInvite',
            field=models.BooleanField(default=False),
        ),
    ]
