# Generated by Django 2.2 on 2021-03-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aki', '0007_auto_20210228_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='flood_control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True)),
                ('timestamp', models.IntegerField()),
                ('count', models.IntegerField()),
            ],
        ),
    ]
