# Generated by Django 2.2 on 2021-03-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aki', '0008_flood_control'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flood_control',
            name='count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='flood_control',
            name='timestamp',
            field=models.IntegerField(null=True),
        ),
    ]
