# Generated by Django 2.2 on 2021-03-15 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aki', '0009_auto_20210308_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='akin',
            name='isNotChild',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='referals',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='who_referal',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
