# Generated by Django 3.1.7 on 2021-04-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aki', '0010_auto_20210315_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='akin',
            name='game_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profiles',
            name='timestamp_register',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='how_referals',
            field=models.IntegerField(blank=True, null=True, verbose_name='Кол-во рефералов'),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='referals',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
