# Generated by Django 3.1.7 on 2021-04-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aki', '0011_auto_20210403_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='timestamp_register',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
