# Generated by Django 3.1.7 on 2021-04-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aki', '0016_auto_20210405_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='timestamp_bonus',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='daily_bonus',
            name='user_id',
            field=models.IntegerField(unique=True),
        ),
    ]
