# Generated by Django 3.1.7 on 2021-04-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aki', '0017_auto_20210405_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily_bonus',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
