# Generated by Django 3.1.7 on 2021-04-05 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aki', '0018_auto_20210405_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profiles',
            name='timestamp_bonus',
        ),
    ]
