# Generated by Django 3.2 on 2021-05-20 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aki', '0011_auto_20210403_1631'),
        ('aki', '0020_profiles_timestamp_bonus'),
    ]

    operations = [
    ]
