# Generated by Django 3.2 on 2021-05-21 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aki', '0023_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='js',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='img',
            field=models.TextField(null=True),
        ),
    ]
