# Generated by Django 3.2 on 2021-05-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aki', '0025_remove_stats_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stats',
            name='date',
            field=models.TextField(unique=True),
        ),
    ]
